## 파일 읽기쓰기

In [16]:

# 'write_example.txt' 파일을 쓰기 모드로 열기
with open('write_example.txt', 'w') as file:
    file.write("Hello, Python!\n")
    file.write("This is an example of writing to a file.\n")

# 파일을 쓰기 모드로 열 때, 'with' 구문을 사용하면 파일을 자동으로 닫아줍니다.


In [17]:
file = open('write_example2.txt', 'w')
file.write("Hello, Python!\n")
file.write("This is an example of writing to a file.\n")
file.close()

In [18]:
# 'write_example.txt' 파일을 쓰기 모드로 열기
with open('write_example.txt', 'w') as file:
    file.write("Hello, Python!\n")
    file.write("This is an example of writing to a file.\n")

# 파일을 쓰기 모드로 열 때, 'with' 구문을 사용하면 파일을 자동으로 닫아줍니다.


In [19]:
# 'write_example.txt' 파일을 추가 모드로 열어 새로운 내용 추가
with open('write_example.txt', 'a') as file:
    file.write("Adding a new line to the file.\n")

# 파일을 다시 읽어 수정된 내용 확인
with open('write_example.txt', 'r') as file:
    content = file.read()
    print(content)


Hello, Python!
This is an example of writing to a file.
Adding a new line to the file.



In [20]:
# 'write_example.txt' 파일을 읽기 모드로 열어 각 줄을 순회하며 출력
with open('write_example.txt', 'r') as file:
    for line in file:
        print(line, end='')  # print 함수는 기본적으로 줄바꿈을 추가하기 때문에, 줄바꿈을 제거합니다.


Hello, Python!
This is an example of writing to a file.
Adding a new line to the file.


In [21]:
# 'write_example.txt' 파일을 읽기 모드로 열어 각 줄을 순회하며 출력
with open('write_example.txt', 'r') as file:
    lines = file.readlines()

In [22]:
lines

['Hello, Python!\n',
 'This is an example of writing to a file.\n',
 'Adding a new line to the file.\n']

In [23]:
import csv

# CSV 파일 쓰기
with open('example.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Name", "Age", "City"])
    writer.writerow(["Alice", "24", "New York"])
    writer.writerow(["Bob", "30", "Los Angeles"])

# CSV 파일 읽기
with open('example.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)


['Name', 'Age', 'City']
['Alice', '24', 'New York']
['Bob', '30', 'Los Angeles']


In [24]:
# CSV 파일 읽기
with open('example.csv', 'r') as file:
    content = file.read()
    print(content)

Name,Age,City
Alice,24,New York
Bob,30,Los Angeles



In [25]:
# CSV 파일 읽기
with open('example.csv', 'r') as file:
    content = [i.strip().split(",") for i in file.readlines()]
    for i in content:
        print(i)

['Name', 'Age', 'City']
['Alice', '24', 'New York']
['Bob', '30', 'Los Angeles']


In [26]:
import json

# JSON 파일 쓰기
data = {
    "name": "Alice",
    "age": 24,
    "city": "New York"
}

with open('data.json', 'w') as file:
    json.dump(data, file)

# JSON 파일 읽기
with open('data.json', 'r') as file:
    data = json.load(file)
    print(data)


{'name': 'Alice', 'age': 24, 'city': 'New York'}


In [27]:
with open('non_existing_file.txt', 'r') as file:
    content = file.read()

FileNotFoundError: [Errno 2] No such file or directory: 'non_existing_file.txt'

In [28]:
try:
    with open('non_existing_file.txt', 'r') as file:
        content = file.read()
except FileNotFoundError:
    print("The file does not exist.")


The file does not exist.


## 외부 라이브러리

In [29]:
# pip install pandas

import pandas as pd

# 데이터프레임 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 30, 18],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)

# 데이터프레임 출력
print(df)

# 데이터프레임에서 조건에 맞는 데이터 선택
print("\nPeople older than 20:")
print(df[df['Age'] > 20])


      Name  Age         City
0    Alice   24     New York
1      Bob   30  Los Angeles
2  Charlie   18      Chicago

People older than 20:
    Name  Age         City
0  Alice   24     New York
1    Bob   30  Los Angeles


In [30]:
df

Name  Age         City
0    Alice   24     New York
1      Bob   30  Los Angeles
2  Charlie   18      Chicago

In [31]:
import requests

# REST API로부터 데이터 가져오기
response = requests.get('https://api.github.com')
data = response.json()

print(data)  # 받아온 JSON 데이터 출력


{'current_user_url': 'https://api.github.com/user', 'current_user_authorizations_html_url': 'https://github.com/settings/connections/applications{/client_id}', 'authorizations_url': 'https://api.github.com/authorizations', 'code_search_url': 'https://api.github.com/search/code?q={query}{&page,per_page,sort,order}', 'commit_search_url': 'https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}', 'emails_url': 'https://api.github.com/user/emails', 'emojis_url': 'https://api.github.com/emojis', 'events_url': 'https://api.github.com/events', 'feeds_url': 'https://api.github.com/feeds', 'followers_url': 'https://api.github.com/user/followers', 'following_url': 'https://api.github.com/user/following{/target}', 'gists_url': 'https://api.github.com/gists{/gist_id}', 'hub_url': 'https://api.github.com/hub', 'issue_search_url': 'https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}', 'issues_url': 'https://api.github.com/issues', 'keys_url': 'https://api.git

In [34]:
import matplotlib.pyplot as plt

# 데이터 준비
x = [1, 2, 3, 4, 5]
y = [2, 3, 5, 7, 11]

# 선 그래프 그리기
plt.plot(x, y)
plt.title('Sample Plot')
plt.xlabel('x')
plt.ylabel('y')
plt.show()


## numpy

In [35]:
import numpy as np

# 1차원 배열 생성
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)

# 2차원 배열 생성
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr_2d)

# 배열의 형태, 차원, 데이터 타입 확인
print("\nArray Shape:", arr_2d.shape)
print("Array Dimensions:", arr_2d.ndim)
print("Array Data Type:", arr_2d.dtype)


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

Array Shape: (2, 3)
Array Dimensions: 2
Array Data Type: int64


In [36]:
# 배열 연산
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 배열 덧셈
print("Addition:", a + b)

# 배열 곱셈
print("Multiplication:", a * b)

# 스칼라와의 연산
print("Scalar Multiplication:", 2 * a)


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Scalar Multiplication: [2 4 6]


In [37]:
# 인덱싱
print("First element of a:", a[0])

# 슬라이싱
print("First two elements of b:", b[:2])

# 조건을 만족하는 요소 선택
print("Elements greater than 2 in a:", a[a > 2])


First element of a: 1
First two elements of b: [4 5]
Elements greater than 2 in a: [3]


In [44]:
a>2

array([False, False,  True])

In [38]:
a[[False, False, True]]

array([3])

In [39]:
# 원래 배열
print("Original Array:\n", arr_2d)

# 배열 형태 변경
reshaped = arr_2d.reshape((3, 2))
print("\nReshaped Array:\n", reshaped)


Original Array:
 [[1 2 3]
 [4 5 6]]

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


In [40]:
reshaped = arr_2d.reshape((1, -1))
reshaped

array([[1, 2, 3, 4, 5, 6]])

In [41]:
# 배열 생성 함수
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
identity_matrix = np.eye(3)

print("Zeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nIdentity Matrix:\n", identity_matrix)

# 통계 함수
print("\nMaximum of a:", np.max(a))
print("Sum of b:", np.sum(b))


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Maximum of a: 3
Sum of b: 15


In [42]:
a

array([1, 2, 3])

In [43]:
b

array([4, 5, 6])